version: '3.9'

services:
  db:
    container_name: db
    hostname: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aidb
      POSTGRES_NAME:
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - airadio
    restart: unless-stopped

  minio:
    container_name: minio
    hostname: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - airadio
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: radiologist
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data

  minio-setup:
    image: minio/mc
    networks:
      - airadio
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 radiologist password;
      /usr/bin/mc mb myminio/public;
      /usr/bin/mc anonymous set download myminio/public;
      exit;
      "



networks:
  airadio:
    driver: bridge

volumes:
  postgres:
  minio_storage: