version: '3.9'

services:
  db:
    container_name: db
    hostname: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aidb
      POSTGRES_NAME:
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - airadio
    restart: unless-stopped


networks:
  airadio:
    driver: bridge

volumes:
  postgres: