// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: rgen.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RGenClient is the client API for RGen service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RGenClient interface {
	GenerateReport(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type rGenClient struct {
	cc grpc.ClientConnInterface
}

func NewRGenClient(cc grpc.ClientConnInterface) RGenClient {
	return &rGenClient{cc}
}

func (c *rGenClient) GenerateReport(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/rgen.RGen/GenerateReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RGenServer is the server API for RGen service.
// All implementations must embed UnimplementedRGenServer
// for forward compatibility
type RGenServer interface {
	GenerateReport(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedRGenServer()
}

// UnimplementedRGenServer must be embedded to have forward compatible implementations.
type UnimplementedRGenServer struct {
}

func (UnimplementedRGenServer) GenerateReport(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateReport not implemented")
}
func (UnimplementedRGenServer) mustEmbedUnimplementedRGenServer() {}

// UnsafeRGenServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RGenServer will
// result in compilation errors.
type UnsafeRGenServer interface {
	mustEmbedUnimplementedRGenServer()
}

func RegisterRGenServer(s grpc.ServiceRegistrar, srv RGenServer) {
	s.RegisterService(&RGen_ServiceDesc, srv)
}

func _RGen_GenerateReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RGenServer).GenerateReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rgen.RGen/GenerateReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RGenServer).GenerateReport(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// RGen_ServiceDesc is the grpc.ServiceDesc for RGen service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RGen_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rgen.RGen",
	HandlerType: (*RGenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateReport",
			Handler:    _RGen_GenerateReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rgen.proto",
}
